import Product from "./product";

export const PRODUCTS: Product[] = [
    {
      id: 1,
      name: "Disque dur SSD 250Go Western Digital Blue",
      brand: "Western Digital",
      barcode: "1987454945248",
      state: "neuf",
      description: "<b>vitesse de lecture</b> : 250Mo/s<br/><b>vitesse d'écriture</b> : 150Mo/s",
      quantity: 2,
      picture: "https://www.cdiscount.com/pdt2/9/2/1/1/550x550/auc8765307756921/rw/disque-dur-ssd-western-digital-wd-blue-ssd-dis.jpg",
      firstCategory: "stockage",
      secondCategory: "disque dur",
      thirdCategory: "SSD",
      price: 20,
      created: new Date(),
      updated: new Date(),
      bestSeller : true
    },
    {
      id: 2,
      name: "SSD 480Go",
      brand: "Western Digital",
      barcode: "19874549452789",
      state: "neuf",
      description: "<table><th>Disque dur SSD de 240Go Western Digital Green<th><tr><td><b>vitesse de lecture</b> : 540Mo/s</td><td><b>vitesse d'écriture</b> : 465Mo/s</td></tr></table>",
      quantity: 5,
      picture: "https://www.cdiscount.com/pdt2/g/0/a/1/300x300/wds480g3g0a/rw/western-digital-green-disque-ssd-interne-480.jpg",
      firstCategory: "stockage",
      secondCategory: "disque dur",
      thirdCategory: "SSD",
      price: 24.99,
      created: new Date(),
      updated: new Date(),
      bestSeller : true
    },
    {
      id: 3,
      name: "HyperX Cloud Alpha",
      brand: "HyperX",
      barcode: "7954574984618951",
      state: "neuf",
      description: "<table><tr><td>Compatible avec PC, PS5, PS4, Xbox One, Xbox Series X|S et d'autres plateformes avec un port de 3,5 mm</td></tr><tr><td>Les transducteurs à chambre double HyperX génèrent un son cristallin et moins de distorsions acoustiques Niveau de pression acoustique : 98dBSPL/mW à 1kHz</td></tr><tr><td>Confort certifié par Discord et TeamSpeak</td></tr><tr><td>Cadre aluminium durable avec arceau élargi</td></tr><tr><td>Câble tressé amovible avec commandes audio en ligne</td></tr><tr><td>Microphone amovible à réduction de bruit</td></tr><tr><td>Impédance: 65 Ω</td></tr><tr><td>Réponse en fréquence : 50Hz-18,000Hz</td></tr><tr><td>Le Cloud Alpha disposant d'un câble détachable, il est également important de s'assurer que ce dernier est complètement inséré dans l'oreillette du casque Aucune partie grise sur la prise jack ne doit être visible une fois le câble branché</td></tr></table>",
      quantity: 3,
      picture: "https://media.hardware.fr/ld/products/00/05/94/75/LD0005947526.jpg",
      firstCategory: "accessoire",
      secondCategory: "casque",
      thirdCategory: "gaming",
      price: 65.99,
      created: new Date(),
      updated: new Date(),
      bestSeller : true
    },
    {
      id: 4,
      name: "Redmi note 12 pro",
      brand: "Xiaomi",
      barcode: "1594854324387",
      state: "neuf",
      description: "<table><tr><td>écran</td><td>AMOLED de 6,67 pouces</td></tr>< tr > <td>taux de rafraîchissement</ td > <td>120 Hz < /td></tr ><tr><td>CPU < /td><td>SoC Mediatek Dimensity 1080</td > </tr>< tr > <td>RAM < /td><td>jusqu'à 8 Go</td > </tr>< tr > <td>stockage < /td><td>256 Go</td > </tr> < tr > <td>batterie < /td><td>5000 mAh</tr ><tr><td>charge rapide < /td><td>compatible 67 W</tr ><th></th>< th > Appareil photo < /th>< tr > trois capteurs à l'arrière </tr>< tr > <td>grand - angle de 50 mégapixels(avec stabilisation optique) < /td></tr ><tr><td>ultra grand - angle de 8 mégapixels < /td></tr ><tr><td>objectif macro de 2 mégapixels < /td></tr ></table>",
      quantity: 1,
      picture: "https://i05.appmifile.com/903_item_fr/12/05/2023/a9f1c00ecd8f61b9dd67801bc8cff0f6!800x800!85.png",
      firstCategory: "téléphone",
      secondCategory: "smartphone",
      thirdCategory: "android",
      price: 209.99,
      created: new Date(),
      updated: new Date(),
      bestSeller : true
    },
    {
      id: 5,
      name: "PlayStation 4",
      brand: "Sony",
      barcode: "15747842488",
      state: "Occasion",
      description: "Console de salon garantie 6 mois",
      quantity: 1,
      picture: "https://m.media-amazon.com/images/I/51x2uufH6SL.jpg",
      firstCategory: "jeuxLoisirs",
      secondCategory: "console",
      thirdCategory: "PS4",
      price: 150,
      created: new Date(),
      updated: new Date(),
      bestSeller: false
    },
    {
      id: 6,
      name: "Seagate Baracuda 2To",
      brand: "Seagate",
      barcode: "19874549122789",
      state: "neuf",
      description: "Disque dur SSD de 2 To",
      quantity: 5,
      picture: "https://m.media-amazon.com/images/I/71icCF9jHLS.jpg",
      firstCategory: "stockage",
      secondCategory: "disque dur",
      thirdCategory: "HDD",
      price: 85,
      created: new Date(),
      updated: new Date(),
      bestSeller : true
    },
  ];